In [1]:
from __future__ import absolute_import, division, print_function

import matplotlib.pyplot as plt
import itertools
import numpy as np

from rmexp import dbutils, config
from rmexp.schema import models

In [2]:
import collections

%matplotlib notebook

sess = dbutils.get_session()
results = [item.val for item in sess.query(models.SS).filter(models.SS.name=="lego_0_905").all()]
cnt=collections.Counter(results)
for (item, freq) in sorted(cnt.items(), key=lambda (k,v): (v,k), reverse=True):
    print('{}:{}'.format(item, freq))
sess.close()

Cannot locate board border, maybe not the full board is in the scene. Failed at stage 1:580
Not confident about reconstruction, maybe too much noise:90
[[2 2 2 2]]:59
[[0 0 1 0]
 [2 2 2 2]]:38
[[0 0 1 6]
 [2 2 2 2]]:34
[[0 2 1 1]
 [0 2 1 6]
 [2 2 2 2]]:30
[[0 2 2 2]
 [0 2 1 1]
 [0 2 1 6]
 [2 2 2 2]]:25
[[0 0 1 1]
 [0 0 1 6]
 [2 2 2 2]]:19
Cannot find a large enough foreground near the center of board:17
[[0 0 1 1]
 [0 2 1 6]
 [2 2 2 2]]:12
Too little black dots with more accurate dot detection. Image may be blurred:1
